### ISSUE TITLE
The interface looks weird in some Firefox versions

### ISSUE THREAD

**Issue by ElenaPT** [DecentralizedScience/Quartz-platform#3]
We have noticed that some parts of the interface for the button are a bit out of place in some browsers. In Firefox 72.0.1, everything looks ok:
![image](https://user-images.githubusercontent.com/16842913/166523950-7ad617a3-557b-4e99-b3cd-309f79d1eb64.png)

The same is true for every version of Chromium we have tested.

However, for newer versions of Firefox, it seems that some things get out of place and the Twitter link does not work at all:
![photo_2022-05-03_21-02-03](https://user-images.githubusercontent.com/16842913/166524318-ba1625d8-0fe1-4a8c-98cc-9751b2422444.jpg)

**Comment by ElenaPT** [comment]
Steps:

- [x] Check in newer versions of Firefox
- [x] Check in different operating systems
- [ ] Study the warnings that appear in the console in the versions that fail

**Comment by atfornes** [comment]
I cannot longer reproduce. I am closing this issue :)
